/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TpRouteImport } from './routes/tp'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as Playout_desknewsRouteImport } from './routes/playout_desknews'
import { Route as PlayoutPgmRouteImport } from './routes/playout-pgm'
import { Route as PlayouTRouteImport } from './routes/playouT'
import { Route as Play_antigo_playoutRouteImport } from './routes/play_antigo_ playout'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginCustomizadoRouteImport } from './routes/login-customizado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EspelhoRouteImport } from './routes/espelho'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as Bk2espelhoRouteImport } from './routes/bk2 espelho'
import { Route as BkplayoutRouteImport } from './routes/bk playout'
import { Route as BkpautasRouteImport } from './routes/bk pautas'
import { Route as BkespelhoRouteImport } from './routes/bk espelho'
import { Route as Bk1espelhoRouteImport } from './routes/bk 1 espelho'
import { Route as XXXplayoutRouteImport } from './routes/XXX playout'
import { Route as VVVplayoutRouteImport } from './routes/VVV playout'
import { Route as UUUplayoutRouteImport } from './routes/UUU playout'
import { Route as ULTIMO_playoutRouteImport } from './routes/ULTIMO _ playout'
import { Route as ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRouteImport } from './routes/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout'
import { Route as TTTplayoutRouteImport } from './routes/TTT playout'
import { Route as SSSplayoutRouteImport } from './routes/SSS playout'
import { Route as RRRplayoutRouteImport } from './routes/RRR playout'
import { Route as MULTIVIEWplayoutRouteImport } from './routes/MULTIVIEW - playout'
import { Route as MULTIVIEWCOMBOTOESplayoutRouteImport } from './routes/MULTI VIEW COM BOTOES - playout'
import { Route as BK2playoutRouteImport } from './routes/BK2 playout'
import { Route as IndexRouteImport } from './routes/index'

const TpRoute = TpRouteImport.update({
  id: '/tp',
  path: '/tp',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const Playout_desknewsRoute = Playout_desknewsRouteImport.update({
  id: '/playout_desknews',
  path: '/playout_desknews',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayoutPgmRoute = PlayoutPgmRouteImport.update({
  id: '/playout-pgm',
  path: '/playout-pgm',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayouTRoute = PlayouTRouteImport.update({
  id: '/playouT',
  path: '/playouT',
  getParentRoute: () => rootRouteImport,
} as any)
const Play_antigo_playoutRoute = Play_antigo_playoutRouteImport.update({
  id: '/play_antigo_ playout',
  path: '/play_antigo_ playout',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCustomizadoRoute = LoginCustomizadoRouteImport.update({
  id: '/login-customizado',
  path: '/login-customizado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhoRoute = EspelhoRouteImport.update({
  id: '/espelho',
  path: '/espelho',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const Bk2espelhoRoute = Bk2espelhoRouteImport.update({
  id: '/bk2 espelho',
  path: '/bk2 espelho',
  getParentRoute: () => rootRouteImport,
} as any)
const BkplayoutRoute = BkplayoutRouteImport.update({
  id: '/bk playout',
  path: '/bk playout',
  getParentRoute: () => rootRouteImport,
} as any)
const BkpautasRoute = BkpautasRouteImport.update({
  id: '/bk pautas',
  path: '/bk pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const BkespelhoRoute = BkespelhoRouteImport.update({
  id: '/bk espelho',
  path: '/bk espelho',
  getParentRoute: () => rootRouteImport,
} as any)
const Bk1espelhoRoute = Bk1espelhoRouteImport.update({
  id: '/bk 1 espelho',
  path: '/bk 1 espelho',
  getParentRoute: () => rootRouteImport,
} as any)
const XXXplayoutRoute = XXXplayoutRouteImport.update({
  id: '/XXX playout',
  path: '/XXX playout',
  getParentRoute: () => rootRouteImport,
} as any)
const VVVplayoutRoute = VVVplayoutRouteImport.update({
  id: '/VVV playout',
  path: '/VVV playout',
  getParentRoute: () => rootRouteImport,
} as any)
const UUUplayoutRoute = UUUplayoutRouteImport.update({
  id: '/UUU playout',
  path: '/UUU playout',
  getParentRoute: () => rootRouteImport,
} as any)
const ULTIMO_playoutRoute = ULTIMO_playoutRouteImport.update({
  id: '/ULTIMO _ playout',
  path: '/ULTIMO _ playout',
  getParentRoute: () => rootRouteImport,
} as any)
const ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute =
  ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRouteImport.update({
    id: '/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout',
    getParentRoute: () => rootRouteImport,
  } as any)
const TTTplayoutRoute = TTTplayoutRouteImport.update({
  id: '/TTT playout',
  path: '/TTT playout',
  getParentRoute: () => rootRouteImport,
} as any)
const SSSplayoutRoute = SSSplayoutRouteImport.update({
  id: '/SSS playout',
  path: '/SSS playout',
  getParentRoute: () => rootRouteImport,
} as any)
const RRRplayoutRoute = RRRplayoutRouteImport.update({
  id: '/RRR playout',
  path: '/RRR playout',
  getParentRoute: () => rootRouteImport,
} as any)
const MULTIVIEWplayoutRoute = MULTIVIEWplayoutRouteImport.update({
  id: '/MULTIVIEW - playout',
  path: '/MULTIVIEW - playout',
  getParentRoute: () => rootRouteImport,
} as any)
const MULTIVIEWCOMBOTOESplayoutRoute =
  MULTIVIEWCOMBOTOESplayoutRouteImport.update({
    id: '/MULTI VIEW COM BOTOES - playout',
    path: '/MULTI VIEW COM BOTOES - playout',
    getParentRoute: () => rootRouteImport,
  } as any)
const BK2playoutRoute = BK2playoutRouteImport.update({
  id: '/BK2 playout',
  path: '/BK2 playout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/BK2 playout': typeof BK2playoutRoute
  '/MULTI VIEW COM BOTOES - playout': typeof MULTIVIEWCOMBOTOESplayoutRoute
  '/MULTIVIEW - playout': typeof MULTIVIEWplayoutRoute
  '/RRR playout': typeof RRRplayoutRoute
  '/SSS playout': typeof SSSplayoutRoute
  '/TTT playout': typeof TTTplayoutRoute
  '/ULTIMA VERSAO playout': typeof ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute
  '/ULTIMO _ playout': typeof ULTIMO_playoutRoute
  '/UUU playout': typeof UUUplayoutRoute
  '/VVV playout': typeof VVVplayoutRoute
  '/XXX playout': typeof XXXplayoutRoute
  '/bk 1 espelho': typeof Bk1espelhoRoute
  '/bk espelho': typeof BkespelhoRoute
  '/bk pautas': typeof BkpautasRoute
  '/bk playout': typeof BkplayoutRoute
  '/bk2 espelho': typeof Bk2espelhoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/login-customizado': typeof LoginCustomizadoRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/play_antigo_ playout': typeof Play_antigo_playoutRoute
  '/playouT': typeof PlayouTRoute
  '/playout-pgm': typeof PlayoutPgmRoute
  '/playout_desknews': typeof Playout_desknewsRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/BK2 playout': typeof BK2playoutRoute
  '/MULTI VIEW COM BOTOES - playout': typeof MULTIVIEWCOMBOTOESplayoutRoute
  '/MULTIVIEW - playout': typeof MULTIVIEWplayoutRoute
  '/RRR playout': typeof RRRplayoutRoute
  '/SSS playout': typeof SSSplayoutRoute
  '/TTT playout': typeof TTTplayoutRoute
  '/ULTIMA VERSAO playout': typeof ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute
  '/ULTIMO _ playout': typeof ULTIMO_playoutRoute
  '/UUU playout': typeof UUUplayoutRoute
  '/VVV playout': typeof VVVplayoutRoute
  '/XXX playout': typeof XXXplayoutRoute
  '/bk 1 espelho': typeof Bk1espelhoRoute
  '/bk espelho': typeof BkespelhoRoute
  '/bk pautas': typeof BkpautasRoute
  '/bk playout': typeof BkplayoutRoute
  '/bk2 espelho': typeof Bk2espelhoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/login-customizado': typeof LoginCustomizadoRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/play_antigo_ playout': typeof Play_antigo_playoutRoute
  '/playouT': typeof PlayouTRoute
  '/playout-pgm': typeof PlayoutPgmRoute
  '/playout_desknews': typeof Playout_desknewsRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/BK2 playout': typeof BK2playoutRoute
  '/MULTI VIEW COM BOTOES - playout': typeof MULTIVIEWCOMBOTOESplayoutRoute
  '/MULTIVIEW - playout': typeof MULTIVIEWplayoutRoute
  '/RRR playout': typeof RRRplayoutRoute
  '/SSS playout': typeof SSSplayoutRoute
  '/TTT playout': typeof TTTplayoutRoute
  '/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout': typeof ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute
  '/ULTIMO _ playout': typeof ULTIMO_playoutRoute
  '/UUU playout': typeof UUUplayoutRoute
  '/VVV playout': typeof VVVplayoutRoute
  '/XXX playout': typeof XXXplayoutRoute
  '/bk 1 espelho': typeof Bk1espelhoRoute
  '/bk espelho': typeof BkespelhoRoute
  '/bk pautas': typeof BkpautasRoute
  '/bk playout': typeof BkplayoutRoute
  '/bk2 espelho': typeof Bk2espelhoRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/login-customizado': typeof LoginCustomizadoRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/play_antigo_ playout': typeof Play_antigo_playoutRoute
  '/playouT': typeof PlayouTRoute
  '/playout-pgm': typeof PlayoutPgmRoute
  '/playout_desknews': typeof Playout_desknewsRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/BK2 playout'
    | '/MULTI VIEW COM BOTOES - playout'
    | '/MULTIVIEW - playout'
    | '/RRR playout'
    | '/SSS playout'
    | '/TTT playout'
    | '/ULTIMA VERSAO playout'
    | '/ULTIMO _ playout'
    | '/UUU playout'
    | '/VVV playout'
    | '/XXX playout'
    | '/bk 1 espelho'
    | '/bk espelho'
    | '/bk pautas'
    | '/bk playout'
    | '/bk2 espelho'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/login-customizado'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/play_antigo_ playout'
    | '/playouT'
    | '/playout-pgm'
    | '/playout_desknews'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/BK2 playout'
    | '/MULTI VIEW COM BOTOES - playout'
    | '/MULTIVIEW - playout'
    | '/RRR playout'
    | '/SSS playout'
    | '/TTT playout'
    | '/ULTIMA VERSAO playout'
    | '/ULTIMO _ playout'
    | '/UUU playout'
    | '/VVV playout'
    | '/XXX playout'
    | '/bk 1 espelho'
    | '/bk espelho'
    | '/bk pautas'
    | '/bk playout'
    | '/bk2 espelho'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/login-customizado'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/play_antigo_ playout'
    | '/playouT'
    | '/playout-pgm'
    | '/playout_desknews'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  id:
    | '__root__'
    | '/'
    | '/BK2 playout'
    | '/MULTI VIEW COM BOTOES - playout'
    | '/MULTIVIEW - playout'
    | '/RRR playout'
    | '/SSS playout'
    | '/TTT playout'
    | '/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout'
    | '/ULTIMO _ playout'
    | '/UUU playout'
    | '/VVV playout'
    | '/XXX playout'
    | '/bk 1 espelho'
    | '/bk espelho'
    | '/bk pautas'
    | '/bk playout'
    | '/bk2 espelho'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/login-customizado'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/play_antigo_ playout'
    | '/playouT'
    | '/playout-pgm'
    | '/playout_desknews'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BK2playoutRoute: typeof BK2playoutRoute
  MULTIVIEWCOMBOTOESplayoutRoute: typeof MULTIVIEWCOMBOTOESplayoutRoute
  MULTIVIEWplayoutRoute: typeof MULTIVIEWplayoutRoute
  RRRplayoutRoute: typeof RRRplayoutRoute
  SSSplayoutRoute: typeof SSSplayoutRoute
  TTTplayoutRoute: typeof TTTplayoutRoute
  ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute: typeof ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute
  ULTIMO_playoutRoute: typeof ULTIMO_playoutRoute
  UUUplayoutRoute: typeof UUUplayoutRoute
  VVVplayoutRoute: typeof VVVplayoutRoute
  XXXplayoutRoute: typeof XXXplayoutRoute
  Bk1espelhoRoute: typeof Bk1espelhoRoute
  BkespelhoRoute: typeof BkespelhoRoute
  BkpautasRoute: typeof BkpautasRoute
  BkplayoutRoute: typeof BkplayoutRoute
  Bk2espelhoRoute: typeof Bk2espelhoRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  EspelhoRoute: typeof EspelhoRoute
  LoginRoute: typeof LoginRoute
  LoginCustomizadoRoute: typeof LoginCustomizadoRoute
  MetricasRoute: typeof MetricasRoute
  PautasRoute: typeof PautasRoute
  PesquisaRoute: typeof PesquisaRoute
  Play_antigo_playoutRoute: typeof Play_antigo_playoutRoute
  PlayouTRoute: typeof PlayouTRoute
  PlayoutPgmRoute: typeof PlayoutPgmRoute
  Playout_desknewsRoute: typeof Playout_desknewsRoute
  RedacaoRoute: typeof RedacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TpRoute: typeof TpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tp': {
      id: '/tp'
      path: '/tp'
      fullPath: '/tp'
      preLoaderRoute: typeof TpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playout_desknews': {
      id: '/playout_desknews'
      path: '/playout_desknews'
      fullPath: '/playout_desknews'
      preLoaderRoute: typeof Playout_desknewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playout-pgm': {
      id: '/playout-pgm'
      path: '/playout-pgm'
      fullPath: '/playout-pgm'
      preLoaderRoute: typeof PlayoutPgmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playouT': {
      id: '/playouT'
      path: '/playouT'
      fullPath: '/playouT'
      preLoaderRoute: typeof PlayouTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play_antigo_ playout': {
      id: '/play_antigo_ playout'
      path: '/play_antigo_ playout'
      fullPath: '/play_antigo_ playout'
      preLoaderRoute: typeof Play_antigo_playoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-customizado': {
      id: '/login-customizado'
      path: '/login-customizado'
      fullPath: '/login-customizado'
      preLoaderRoute: typeof LoginCustomizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelho': {
      id: '/espelho'
      path: '/espelho'
      fullPath: '/espelho'
      preLoaderRoute: typeof EspelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk2 espelho': {
      id: '/bk2 espelho'
      path: '/bk2 espelho'
      fullPath: '/bk2 espelho'
      preLoaderRoute: typeof Bk2espelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk playout': {
      id: '/bk playout'
      path: '/bk playout'
      fullPath: '/bk playout'
      preLoaderRoute: typeof BkplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk pautas': {
      id: '/bk pautas'
      path: '/bk pautas'
      fullPath: '/bk pautas'
      preLoaderRoute: typeof BkpautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk espelho': {
      id: '/bk espelho'
      path: '/bk espelho'
      fullPath: '/bk espelho'
      preLoaderRoute: typeof BkespelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bk 1 espelho': {
      id: '/bk 1 espelho'
      path: '/bk 1 espelho'
      fullPath: '/bk 1 espelho'
      preLoaderRoute: typeof Bk1espelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/XXX playout': {
      id: '/XXX playout'
      path: '/XXX playout'
      fullPath: '/XXX playout'
      preLoaderRoute: typeof XXXplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/VVV playout': {
      id: '/VVV playout'
      path: '/VVV playout'
      fullPath: '/VVV playout'
      preLoaderRoute: typeof VVVplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UUU playout': {
      id: '/UUU playout'
      path: '/UUU playout'
      fullPath: '/UUU playout'
      preLoaderRoute: typeof UUUplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ULTIMO _ playout': {
      id: '/ULTIMO _ playout'
      path: '/ULTIMO _ playout'
      fullPath: '/ULTIMO _ playout'
      preLoaderRoute: typeof ULTIMO_playoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout': {
      id: '/ULTIMA VERSAO (COM MULTI IMPORTANDO)playout'
      path: '/ULTIMA VERSAO playout'
      fullPath: '/ULTIMA VERSAO playout'
      preLoaderRoute: typeof ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TTT playout': {
      id: '/TTT playout'
      path: '/TTT playout'
      fullPath: '/TTT playout'
      preLoaderRoute: typeof TTTplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SSS playout': {
      id: '/SSS playout'
      path: '/SSS playout'
      fullPath: '/SSS playout'
      preLoaderRoute: typeof SSSplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RRR playout': {
      id: '/RRR playout'
      path: '/RRR playout'
      fullPath: '/RRR playout'
      preLoaderRoute: typeof RRRplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MULTIVIEW - playout': {
      id: '/MULTIVIEW - playout'
      path: '/MULTIVIEW - playout'
      fullPath: '/MULTIVIEW - playout'
      preLoaderRoute: typeof MULTIVIEWplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MULTI VIEW COM BOTOES - playout': {
      id: '/MULTI VIEW COM BOTOES - playout'
      path: '/MULTI VIEW COM BOTOES - playout'
      fullPath: '/MULTI VIEW COM BOTOES - playout'
      preLoaderRoute: typeof MULTIVIEWCOMBOTOESplayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/BK2 playout': {
      id: '/BK2 playout'
      path: '/BK2 playout'
      fullPath: '/BK2 playout'
      preLoaderRoute: typeof BK2playoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BK2playoutRoute: BK2playoutRoute,
  MULTIVIEWCOMBOTOESplayoutRoute: MULTIVIEWCOMBOTOESplayoutRoute,
  MULTIVIEWplayoutRoute: MULTIVIEWplayoutRoute,
  RRRplayoutRoute: RRRplayoutRoute,
  SSSplayoutRoute: SSSplayoutRoute,
  TTTplayoutRoute: TTTplayoutRoute,
  ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute:
    ULTIMAVERSAOCOMMULTIIMPORTANDOplayoutRoute,
  ULTIMO_playoutRoute: ULTIMO_playoutRoute,
  UUUplayoutRoute: UUUplayoutRoute,
  VVVplayoutRoute: VVVplayoutRoute,
  XXXplayoutRoute: XXXplayoutRoute,
  Bk1espelhoRoute: Bk1espelhoRoute,
  BkespelhoRoute: BkespelhoRoute,
  BkpautasRoute: BkpautasRoute,
  BkplayoutRoute: BkplayoutRoute,
  Bk2espelhoRoute: Bk2espelhoRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  EspelhoRoute: EspelhoRoute,
  LoginRoute: LoginRoute,
  LoginCustomizadoRoute: LoginCustomizadoRoute,
  MetricasRoute: MetricasRoute,
  PautasRoute: PautasRoute,
  PesquisaRoute: PesquisaRoute,
  Play_antigo_playoutRoute: Play_antigo_playoutRoute,
  PlayouTRoute: PlayouTRoute,
  PlayoutPgmRoute: PlayoutPgmRoute,
  Playout_desknewsRoute: Playout_desknewsRoute,
  RedacaoRoute: RedacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  TpRoute: TpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
