/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TpRouteImport } from './routes/tp'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as PlayouTRouteImport } from './routes/playouT'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EspelhoRouteImport } from './routes/espelho'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const TpRoute = TpRouteImport.update({
  id: '/tp',
  path: '/tp',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayouTRoute = PlayouTRouteImport.update({
  id: '/playouT',
  path: '/playouT',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EspelhoRoute = EspelhoRouteImport.update({
  id: '/espelho',
  path: '/espelho',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/playouT': typeof PlayouTRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/playouT': typeof PlayouTRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dashboard': typeof DashboardRoute
  '/espelho': typeof EspelhoRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/pautas': typeof PautasRoute
  '/pesquisa': typeof PesquisaRoute
  '/playouT': typeof PlayouTRoute
  '/redacao': typeof RedacaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/tp': typeof TpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/playouT'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/playouT'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/dashboard'
    | '/espelho'
    | '/login'
    | '/metricas'
    | '/pautas'
    | '/pesquisa'
    | '/playouT'
    | '/redacao'
    | '/relatorios'
    | '/tp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DashboardRoute: typeof DashboardRoute
  EspelhoRoute: typeof EspelhoRoute
  LoginRoute: typeof LoginRoute
  MetricasRoute: typeof MetricasRoute
  PautasRoute: typeof PautasRoute
  PesquisaRoute: typeof PesquisaRoute
  PlayouTRoute: typeof PlayouTRoute
  RedacaoRoute: typeof RedacaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TpRoute: typeof TpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tp': {
      id: '/tp'
      path: '/tp'
      fullPath: '/tp'
      preLoaderRoute: typeof TpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playouT': {
      id: '/playouT'
      path: '/playouT'
      fullPath: '/playouT'
      preLoaderRoute: typeof PlayouTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espelho': {
      id: '/espelho'
      path: '/espelho'
      fullPath: '/espelho'
      preLoaderRoute: typeof EspelhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DashboardRoute: DashboardRoute,
  EspelhoRoute: EspelhoRoute,
  LoginRoute: LoginRoute,
  MetricasRoute: MetricasRoute,
  PautasRoute: PautasRoute,
  PesquisaRoute: PesquisaRoute,
  PlayouTRoute: PlayouTRoute,
  RedacaoRoute: RedacaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  TpRoute: TpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
